"""pivot_to_projects

Revision ID: 29ce435bc869
Revises: fe275d81b8dd
Create Date: 2026-06-11 15:38:28.469265

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '29ce435bc869'
down_revision: Union[str, Sequence[str], None] = 'fe275d81b8dd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('club_members')
    op.drop_index(op.f('ix_clubs_id'), table_name='clubs')
    op.drop_index(op.f('ix_clubs_invite_code'), table_name='clubs')
    op.drop_table('clubs')
    op.drop_index(op.f('ix_club_feed_messages_id'), table_name='club_feed_messages')
    op.drop_table('club_feed_messages')
    op.drop_index(op.f('ix_club_tasks_id'), table_name='club_tasks')
    op.drop_table('club_tasks')
    op.drop_index(op.f('ix_club_task_completions_id'), table_name='club_task_completions')
    op.drop_table('club_task_completions')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('club_task_completions',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('club_task_id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('completed_at', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['club_task_id'], ['club_tasks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_club_task_completions_id'), 'club_task_completions', ['id'], unique=False)
    op.create_table('club_tasks',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('club_id', sa.INTEGER(), nullable=False),
    sa.Column('title', sa.VARCHAR(length=200), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('task_type', sa.VARCHAR(length=50), nullable=False),
    sa.Column('xp_reward', sa.INTEGER(), nullable=False),
    sa.Column('due_date', sa.DATETIME(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['club_id'], ['clubs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_club_tasks_id'), 'club_tasks', ['id'], unique=False)
    op.create_table('club_feed_messages',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('club_id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('content', sa.TEXT(), nullable=False),
    sa.Column('is_achievement', sa.BOOLEAN(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['club_id'], ['clubs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_club_feed_messages_id'), 'club_feed_messages', ['id'], unique=False)
    op.create_table('clubs',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('invite_code', sa.VARCHAR(length=50), nullable=False),
    sa.Column('owner_id', sa.INTEGER(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clubs_invite_code'), 'clubs', ['invite_code'], unique=1)
    op.create_index(op.f('ix_clubs_id'), 'clubs', ['id'], unique=False)
    op.create_table('club_members',
    sa.Column('club_id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('role', sa.VARCHAR(length=20), nullable=False),
    sa.Column('points_earned', sa.INTEGER(), nullable=False),
    sa.Column('joined_at', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['club_id'], ['clubs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('club_id', 'user_id')
    )
    # ### end Alembic commands ###
