"""add whatsapp settings to user

Revision ID: 5f8b9ad18165
Revises: 29ce435bc869
Create Date: 2026-06-11 16:41:43.528690

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5f8b9ad18165'
down_revision: Union[str, Sequence[str], None] = '29ce435bc869'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('whatsapp_phone', sa.String(), nullable=True))
    op.add_column('users', sa.Column('whatsapp_active', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('whatsapp_sandbox', sa.String(), nullable=True))
    op.add_column('users', sa.Column('ai_provider', sa.String(), nullable=True))
    op.add_column('users', sa.Column('ai_model', sa.String(), nullable=True))
    op.add_column('users', sa.Column('ai_api_key', sa.String(), nullable=True))
    op.create_index(op.f('ix_users_whatsapp_phone'), 'users', ['whatsapp_phone'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_whatsapp_phone'), table_name='users')
    op.drop_column('users', 'ai_api_key')
    op.drop_column('users', 'ai_model')
    op.drop_column('users', 'ai_provider')
    op.drop_column('users', 'whatsapp_sandbox')
    op.drop_column('users', 'whatsapp_active')
    op.drop_column('users', 'whatsapp_phone')
    # ### end Alembic commands ###
