"""add_user_password_reset_fields

Revision ID: c5a6b9252d64
Revises: d0e1eea6f91a
Create Date: 2026-08-18 19:45:48.537400

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c5a6b9252d64'
down_revision: Union[str, Sequence[str], None] = 'd0e1eea6f91a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('reset_token', sa.String(), nullable=True))
    op.add_column('users', sa.Column('reset_token_expires_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'reset_token_expires_at')
    op.drop_column('users', 'reset_token')
    # ### end Alembic commands ###
